### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Gustl22** [Oberhauser-Dev/wrestling_scoreboard#74]
Bei der Organisation "Bayerischer Ringerverband e. V." war in der Bayernliga keine Mannschaft und keine Begegnungen.
Habe dann eine neue Organisation "Test Christian" angelegt. Wäre cool, wenn der Sync-Vorgang gleich beim Anlegen abgefragt wird. Den Button rechts oben sieht man kaum bzw. habe ich lange gesucht. Leider hat er bei mir auch nicht funktioniert.

Cool ist, dass es 2 Möglichkeiten gibt, wie man zum Kampf kommt (über Spielklassen und auch über den Verein). Bei einer Begegnung Kämpfe hinzufügen finde ich kompliziert. Da hätte ich mir eine möglichst vorausgefüllte Tabelle gewünscht. Leider hat es bei mir nicht geklappt einen Kampf hinzuzufügen.

AZ und VZ finde ich ziemlich klein. Denke das ist in dem Moment wo es angezeigt wird relativ wichtig und sollte vllt größer sein, damit man es auf den Rängen noch sieht.

**Comment by Gustl22** [comment]
- [ ] ERROR #1

```
RestException: Failed to import from team_match 40:
	Reason:  (500):
	Body: {"err": "InvalidParameterException(message: "Bout with id "120" not found")", "stackTrace": "#0      EntityController.getSingleRaw (package:wrestling_scoreboard_server/controllers/entity_controller.dart:312)
<asynchronous suspension>
#1      BoutController.deleteSingle (package:wrestling_scoreboard_server/controllers/bout_controller.dart:31)
<asynchronous suspension>
#2      TeamMatchController.import.<anonymous closure> (package:wrestling_scoreboard_server/controllers/team_match_controller.dart:206)
<asynchronous suspension>
#3      OrganizationalController.updateOrCreateManyOfOrg.<anonymous closure> (package:wrestling_scoreboard_server/controllers/organizational_controller.dart:85)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534)
<asynchronous suspension>
#5      OrganizationalController.updateOrCreateManyOfOrg (package:wrestling_scoreboard_server/controllers/organizational_controller.dart:83)
<asynchronous suspension>
#6      TeamMatchController.import (package:wrestling_scoreboard_server/controllers/team_match_controller.dart:164)
<asynchronous suspension>
#7      ImportController.postImport (package:wrestling_scoreboard_server/controllers/entity_controller.dart:97)
<asynchronous suspension>
#8      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:109)
<asynchronous suspension>
#9      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#10     Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#11     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:71)
<asynchronous suspension>
#12     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:107)
<asynchronous suspension>
#13     RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#14     Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#15     logRequests.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware/logger.dart:30)
<asynchronous suspension>
#16     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:71)
<asynchronous suspension>
#17     handleRequest (package:shelf/shelf_io.dart:138)
<asynchronous suspension>
"}
```

- [ ] ERROR #2
Make migration after import

```
ERROR - 2024-11-23 19:23:19.524907
GET /api/organization/2
Error thrown by handler.
Severity.error Session or transaction has already finished, did you forget to await a statement?
package:postgres/src/v3/connection.dart 56:7                                   _PgSessionBase._checkActive
package:postgres/src/v3/connection.dart 66:5                                   _PgSessionBase._withResource
package:postgres/src/v3/connection.dart 673:21                                 _PgResultStreamSubscription._scheduleStatement
package:postgres/src/v3/connection.dart 629:5                                  new _PgResultStreamSubscription
package:postgres/src/v3/connection.dart 600:12                                 _BoundStatement.listen
dart:async                                                                     Stream.toList
package:wrestling_scoreboard_server/controllers/entity_controller.dart 311:48  EntityController.getSingleRaw
package:wrestling_scoreboard_server/controllers/entity_controller.dart 301:26  EntityController.getSingle
package:wrestling_scoreboard_server/controllers/entity_controller.dart 141:28  ShelfController.handleRequestSingle
package:wrestling_scoreboard_server/controllers/entity_controller.dart 118:12  ShelfController.requestSingle
package:wrestling_scoreboard_server/routes/router.dart 14:105                  RestrictedRouter.restrictedGetOne.<fn>.<fn>
package:wrestling_scoreboard_server/services/auth.dart 32:21                   AuthRequest.restricted
```

- [ ] ERROR #3
Pressing esc on open menu in lineup edit leads to stuck screen

- [ ] ERROR #4
Ringkampf Abfolge:
57 F
61 G

2. Runde:
57 F


- [ ] ERROR #5
Leg Foul Beinarbeit in G L


- [ ] ERROR #6 Null value used in a non nullable variable: Somehow may reproducible in bouts when playing around with timers
[log] Websocket connection established: ws://localhost:8080/ws
[ERROR:flutter/shell/common/shell.cc(1065)] The 'xyz.luan/audioplayers/events/7bed8c3c-1506-4fdf-9af1-240715b08789' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.


- [ ] ERROR #7 Does not save Language

**Comment by Gustl22** [comment]
- [ ] doppelte aus Test datenbank entfernen, z.B. 9430
- [ ] 5906 unter suche bei Peter Totok
- [ ] Neue Ringer direkt im Lineup hinzufügen
- [ ] Zeit Rückwärts wird nicht ganz korrekt berechnet
- [ ] TÜ wird abgespeichert, wenn zum nächsten Kampf gegangen wird, dann wieder revidiert
